spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/test31
    username: postgres
    password: 123
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 332992138196-9havmvn4qov82t04g8emma3arv8rs3e7.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - profile
              - email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://www.googleapis.com/oauth2/v4/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
            user-name-attribute: sub
ehcache:
  config: classpath:ehcache.xml
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.example: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
