server:
  port: 8082
message: "PROD config"
my:
  prod:
    property: "Prod"
  spring:
    datasource:
      url: jdbc:postgresql://localhost:5432/test31_dev
      username: postgres
      password: 123
      driver-class-name: org.postgresql.Driver
