server:
  port: 8080
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 623985751790-ovju6qp7lvka7njmra3kkv9tti9m76pe.apps.googleusercontent.com
            client-secret: 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
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - profile
              - email
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://www.googleapis.com/oauth2/v4/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
            user-name-attribute: sub
ehcache:
  config: classpath:ehcache.xml
logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    com.example: TRACE
    org.springframework.security: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
